# To validate:
#   cat codecov.yml | curl --data-binary @- https://codecov.io/validate

codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "50...80"

  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        enabled: no # disable patch since it is noisy and not correct
        if_not_found: success

comment: false