// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: liquidity.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type LiquidityPoolType struct {
	// index of target pool type, only 1 is allowed on this version.
	PoolTypeIndex uint32 `protobuf:"varint,1,opt,name=pool_type_index,json=poolTypeIndex,proto3" json:"pool_type_index,omitempty" yaml:"pool_type_index"`
	// name of the pool type
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" yaml:"name"`
	// min number of reserveCoins for LiquidityPoolType only 2 is allowed on this spec
	MinReserveCoinNum uint32 `protobuf:"varint,3,opt,name=min_reserve_coin_num,json=minReserveCoinNum,proto3" json:"min_reserve_coin_num,omitempty" yaml:"min_reserve_coin_num"`
	// max number of reserveCoins for LiquidityPoolType only 2 is allowed on this spec
	MaxReserveCoinNum uint32 `protobuf:"varint,4,opt,name=max_reserve_coin_num,json=maxReserveCoinNum,proto3" json:"max_reserve_coin_num,omitempty" yaml:"max_reserve_coin_num"`
	// description of the pool type
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty" yaml:"description"`
}

func (m *LiquidityPoolType) Reset()         { *m = LiquidityPoolType{} }
func (m *LiquidityPoolType) String() string { return proto.CompactTextString(m) }
func (*LiquidityPoolType) ProtoMessage()    {}
func (*LiquidityPoolType) Descriptor() ([]byte, []int) {
	return fileDescriptor_65b46dab34d3c00e, []int{0}
}
func (m *LiquidityPoolType) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LiquidityPoolType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LiquidityPoolType.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LiquidityPoolType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiquidityPoolType.Merge(m, src)
}
func (m *LiquidityPoolType) XXX_Size() int {
	return m.Size()
}
func (m *LiquidityPoolType) XXX_DiscardUnknown() {
	xxx_messageInfo_LiquidityPoolType.DiscardUnknown(m)
}

var xxx_messageInfo_LiquidityPoolType proto.InternalMessageInfo

type Params struct {
	// list of available pool types
	LiquidityPoolTypes []LiquidityPoolType `protobuf:"bytes,1,rep,name=liquidity_pool_types,json=liquidityPoolTypes,proto3" json:"liquidity_pool_types" yaml:"liquidity_pool_types"`
	// Minimum number of coins to be deposited to the liquidity pool upon pool creation
	MinInitDepositToPool github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,2,opt,name=min_init_deposit_to_pool,json=minInitDepositToPool,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"min_init_deposit_to_pool" yaml:"min_init_deposit_to_pool"`
	// Initial mint amount of pool coin upon pool creation
	InitPoolCoinMintAmount github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,3,opt,name=init_pool_coin_mint_amount,json=initPoolCoinMintAmount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"init_pool_coin_mint_amount" yaml:"init_pool_coin_mint_amount"`
	// Swap fee rate for every executed swap
	SwapFeeRate github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,4,opt,name=swap_fee_rate,json=swapFeeRate,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"swap_fee_rate" yaml:"swap_fee_rate"`
	// Fee paid for new LiquidityPool creation to prevent spamming
	LiquidityPoolCreationFee github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,5,rep,name=liquidity_pool_creation_fee,json=liquidityPoolCreationFee,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"liquidity_pool_creation_fee" yaml:"liquidity_pool_creation_fee"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_65b46dab34d3c00e, []int{1}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

type LiquidityPool struct {
	// id of the pool
	PoolId uint64 `protobuf:"varint,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id" yaml:"pool_id"`
	// index of the pool type
	PoolTypeIndex uint32 `protobuf:"varint,2,opt,name=pool_type_index,json=poolTypeIndex,proto3" json:"pool_type_index,omitempty" yaml:"pool_type_index"`
	// denoms of reserve coin pair of the pool
	ReserveCoinDenoms []string `protobuf:"bytes,3,rep,name=reserve_coin_denoms,json=reserveCoinDenoms,proto3" json:"reserve_coin_denoms,omitempty" yaml:"reserve_coin_denoms"`
	// reserve account address of the pool
	ReserveAccountAddress string `protobuf:"bytes,4,opt,name=reserve_account_address,json=reserveAccountAddress,proto3" json:"reserve_account_address,omitempty" yaml:"reserve_account_address"`
	// denom of pool coin of the pool
	PoolCoinDenom string `protobuf:"bytes,5,opt,name=pool_coin_denom,json=poolCoinDenom,proto3" json:"pool_coin_denom,omitempty" yaml:"pool_coin_denom"`
}

func (m *LiquidityPool) Reset()         { *m = LiquidityPool{} }
func (m *LiquidityPool) String() string { return proto.CompactTextString(m) }
func (*LiquidityPool) ProtoMessage()    {}
func (*LiquidityPool) Descriptor() ([]byte, []int) {
	return fileDescriptor_65b46dab34d3c00e, []int{2}
}
func (m *LiquidityPool) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LiquidityPool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LiquidityPool.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LiquidityPool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiquidityPool.Merge(m, src)
}
func (m *LiquidityPool) XXX_Size() int {
	return m.Size()
}
func (m *LiquidityPool) XXX_DiscardUnknown() {
	xxx_messageInfo_LiquidityPool.DiscardUnknown(m)
}

var xxx_messageInfo_LiquidityPool proto.InternalMessageInfo

type LiquidityPoolMetadata struct {
	// id of the pool
	PoolId uint64 `protobuf:"varint,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id" yaml:"pool_id"`
	// pool coin issued at the pool
	PoolCoinTotalSupply types.Coin `protobuf:"bytes,2,opt,name=pool_coin_total_supply,json=poolCoinTotalSupply,proto3" json:"pool_coin_total_supply" yaml:"pool_coin_total_supply"`
	// reserve coins deposited in the pool
	ReserveCoins github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,3,rep,name=reserve_coins,json=reserveCoins,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"reserve_coins" yaml:"reserve_coins"`
}

func (m *LiquidityPoolMetadata) Reset()         { *m = LiquidityPoolMetadata{} }
func (m *LiquidityPoolMetadata) String() string { return proto.CompactTextString(m) }
func (*LiquidityPoolMetadata) ProtoMessage()    {}
func (*LiquidityPoolMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_65b46dab34d3c00e, []int{3}
}
func (m *LiquidityPoolMetadata) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LiquidityPoolMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LiquidityPoolMetadata.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LiquidityPoolMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiquidityPoolMetadata.Merge(m, src)
}
func (m *LiquidityPoolMetadata) XXX_Size() int {
	return m.Size()
}
func (m *LiquidityPoolMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_LiquidityPoolMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_LiquidityPoolMetadata proto.InternalMessageInfo

type LiquidityPoolBatch struct {
	// id of the pool
	PoolId uint64 `protobuf:"varint,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id" yaml:"pool_id"`
	// index of this batch
	BatchIndex uint64 `protobuf:"varint,2,opt,name=batch_index,json=batchIndex,proto3" json:"batch_index,omitempty" yaml:"batch_index"`
	// height where this batch is begun
	BeginHeight int64 `protobuf:"varint,3,opt,name=begin_height,json=beginHeight,proto3" json:"begin_height,omitempty" yaml:"begin_height"`
	// last index of BatchPoolDepositMsgs
	DepositMsgIndex uint64 `protobuf:"varint,4,opt,name=deposit_msg_index,json=depositMsgIndex,proto3" json:"deposit_msg_index,omitempty" yaml:"deposit_msg_index"`
	// last index of BatchPoolWithdrawMsgs
	WithdrawMsgIndex uint64 `protobuf:"varint,5,opt,name=withdraw_msg_index,json=withdrawMsgIndex,proto3" json:"withdraw_msg_index,omitempty" yaml:"withdraw_msg_index"`
	// last index of BatchPoolSwapMsgs
	SwapMsgIndex uint64 `protobuf:"varint,6,opt,name=swap_msg_index,json=swapMsgIndex,proto3" json:"swap_msg_index,omitempty" yaml:"swap_msg_index"`
	// true if executed, false if not executed yet
	Executed bool `protobuf:"varint,7,opt,name=executed,proto3" json:"executed,omitempty" yaml:"executed"`
}

func (m *LiquidityPoolBatch) Reset()         { *m = LiquidityPoolBatch{} }
func (m *LiquidityPoolBatch) String() string { return proto.CompactTextString(m) }
func (*LiquidityPoolBatch) ProtoMessage()    {}
func (*LiquidityPoolBatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_65b46dab34d3c00e, []int{4}
}
func (m *LiquidityPoolBatch) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LiquidityPoolBatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LiquidityPoolBatch.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LiquidityPoolBatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiquidityPoolBatch.Merge(m, src)
}
func (m *LiquidityPoolBatch) XXX_Size() int {
	return m.Size()
}
func (m *LiquidityPoolBatch) XXX_DiscardUnknown() {
	xxx_messageInfo_LiquidityPoolBatch.DiscardUnknown(m)
}

var xxx_messageInfo_LiquidityPoolBatch proto.InternalMessageInfo

type BatchPoolDepositMsg struct {
	// height where this message is appended to the batch
	MsgHeight int64 `protobuf:"varint,1,opt,name=msg_height,json=msgHeight,proto3" json:"msg_height,omitempty" yaml:"msg_height"`
	// index of this deposit message in this liquidity pool
	MsgIndex uint64 `protobuf:"varint,2,opt,name=msg_index,json=msgIndex,proto3" json:"msg_index,omitempty" yaml:"msg_index"`
	// true if executed on this batch, false if not executed yet
	Executed bool `protobuf:"varint,3,opt,name=executed,proto3" json:"executed,omitempty" yaml:"executed"`
	// true if executed successfully on this batch, false if failed
	Succeed bool `protobuf:"varint,4,opt,name=succeed,proto3" json:"succeed,omitempty" yaml:"succeed"`
	// true if ready to delete on kvstore, false if not ready to delete
	ToDelete bool `protobuf:"varint,5,opt,name=to_delete,json=toDelete,proto3" json:"to_delete,omitempty" yaml:"to_delete"`
	// MsgDepositToLiquidityPool
	Msg *MsgDepositToLiquidityPool `protobuf:"bytes,6,opt,name=msg,proto3" json:"msg,omitempty" yaml:"msg"`
}

func (m *BatchPoolDepositMsg) Reset()         { *m = BatchPoolDepositMsg{} }
func (m *BatchPoolDepositMsg) String() string { return proto.CompactTextString(m) }
func (*BatchPoolDepositMsg) ProtoMessage()    {}
func (*BatchPoolDepositMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_65b46dab34d3c00e, []int{5}
}
func (m *BatchPoolDepositMsg) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BatchPoolDepositMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BatchPoolDepositMsg.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BatchPoolDepositMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchPoolDepositMsg.Merge(m, src)
}
func (m *BatchPoolDepositMsg) XXX_Size() int {
	return m.Size()
}
func (m *BatchPoolDepositMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchPoolDepositMsg.DiscardUnknown(m)
}

var xxx_messageInfo_BatchPoolDepositMsg proto.InternalMessageInfo

type BatchPoolWithdrawMsg struct {
	// height where this message is appended to the batch
	MsgHeight int64 `protobuf:"varint,1,opt,name=msg_height,json=msgHeight,proto3" json:"msg_height,omitempty" yaml:"msg_height"`
	// index of this withdraw message in this liquidity pool
	MsgIndex uint64 `protobuf:"varint,2,opt,name=msg_index,json=msgIndex,proto3" json:"msg_index,omitempty" yaml:"msg_index"`
	// true if executed on this batch, false if not executed yet
	Executed bool `protobuf:"varint,3,opt,name=executed,proto3" json:"executed,omitempty" yaml:"executed"`
	// true if executed successfully on this batch, false if failed
	Succeed bool `protobuf:"varint,4,opt,name=succeed,proto3" json:"succeed,omitempty" yaml:"succeed"`
	// true if ready to delete on kvstore, false if not ready to delete
	ToDelete bool `protobuf:"varint,5,opt,name=to_delete,json=toDelete,proto3" json:"to_delete,omitempty" yaml:"to_delete"`
	// MsgWithdrawFromLiquidityPool
	Msg *MsgWithdrawFromLiquidityPool `protobuf:"bytes,6,opt,name=msg,proto3" json:"msg,omitempty" yaml:"msg"`
}

func (m *BatchPoolWithdrawMsg) Reset()         { *m = BatchPoolWithdrawMsg{} }
func (m *BatchPoolWithdrawMsg) String() string { return proto.CompactTextString(m) }
func (*BatchPoolWithdrawMsg) ProtoMessage()    {}
func (*BatchPoolWithdrawMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_65b46dab34d3c00e, []int{6}
}
func (m *BatchPoolWithdrawMsg) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BatchPoolWithdrawMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BatchPoolWithdrawMsg.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BatchPoolWithdrawMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchPoolWithdrawMsg.Merge(m, src)
}
func (m *BatchPoolWithdrawMsg) XXX_Size() int {
	return m.Size()
}
func (m *BatchPoolWithdrawMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchPoolWithdrawMsg.DiscardUnknown(m)
}

var xxx_messageInfo_BatchPoolWithdrawMsg proto.InternalMessageInfo

type BatchPoolSwapMsg struct {
	// height where this message is appended to the batch
	MsgHeight int64 `protobuf:"varint,1,opt,name=msg_height,json=msgHeight,proto3" json:"msg_height,omitempty" yaml:"msg_height"`
	// index of this swap message in this liquidity pool
	MsgIndex uint64 `protobuf:"varint,2,opt,name=msg_index,json=msgIndex,proto3" json:"msg_index,omitempty" yaml:"msg_index"`
	// true if executed on this batch, false if not executed yet
	Executed bool `protobuf:"varint,3,opt,name=executed,proto3" json:"executed,omitempty" yaml:"executed"`
	// true if executed successfully on this batch, false if failed
	Succeed bool `protobuf:"varint,4,opt,name=succeed,proto3" json:"succeed,omitempty" yaml:"succeed"`
	// true if ready to delete on kvstore, false if not ready to delete
	ToDelete bool `protobuf:"varint,5,opt,name=to_delete,json=toDelete,proto3" json:"to_delete,omitempty" yaml:"to_delete"`
	// swap orders are cancelled when current height is equal or higher than ExpiryHeight
	OrderExpiryHeight int64 `protobuf:"varint,6,opt,name=order_expiry_height,json=orderExpiryHeight,proto3" json:"order_expiry_height,omitempty" yaml:"order_expiry_height"`
	// offer coin exchanged until now
	ExchangedOfferCoin types.Coin `protobuf:"bytes,7,opt,name=exchanged_offer_coin,json=exchangedOfferCoin,proto3" json:"exchanged_offer_coin" yaml:"exchanged_offer_coin"`
	// offer coin currently remaining to be exchanged
	RemainingOfferCoin types.Coin `protobuf:"bytes,8,opt,name=remaining_offer_coin,json=remainingOfferCoin,proto3" json:"remaining_offer_coin" yaml:"remaining_offer_coin"`
	// MsgSwap
	Msg *MsgSwap `protobuf:"bytes,9,opt,name=msg,proto3" json:"msg,omitempty" yaml:"msg"`
}

func (m *BatchPoolSwapMsg) Reset()         { *m = BatchPoolSwapMsg{} }
func (m *BatchPoolSwapMsg) String() string { return proto.CompactTextString(m) }
func (*BatchPoolSwapMsg) ProtoMessage()    {}
func (*BatchPoolSwapMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_65b46dab34d3c00e, []int{7}
}
func (m *BatchPoolSwapMsg) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BatchPoolSwapMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BatchPoolSwapMsg.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BatchPoolSwapMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchPoolSwapMsg.Merge(m, src)
}
func (m *BatchPoolSwapMsg) XXX_Size() int {
	return m.Size()
}
func (m *BatchPoolSwapMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchPoolSwapMsg.DiscardUnknown(m)
}

var xxx_messageInfo_BatchPoolSwapMsg proto.InternalMessageInfo

func init() {
	proto.RegisterType((*LiquidityPoolType)(nil), "tendermint.liquidity.LiquidityPoolType")
	proto.RegisterType((*Params)(nil), "tendermint.liquidity.Params")
	proto.RegisterType((*LiquidityPool)(nil), "tendermint.liquidity.LiquidityPool")
	proto.RegisterType((*LiquidityPoolMetadata)(nil), "tendermint.liquidity.LiquidityPoolMetadata")
	proto.RegisterType((*LiquidityPoolBatch)(nil), "tendermint.liquidity.LiquidityPoolBatch")
	proto.RegisterType((*BatchPoolDepositMsg)(nil), "tendermint.liquidity.BatchPoolDepositMsg")
	proto.RegisterType((*BatchPoolWithdrawMsg)(nil), "tendermint.liquidity.BatchPoolWithdrawMsg")
	proto.RegisterType((*BatchPoolSwapMsg)(nil), "tendermint.liquidity.BatchPoolSwapMsg")
}

func init() { proto.RegisterFile("liquidity.proto", fileDescriptor_65b46dab34d3c00e) }

var fileDescriptor_65b46dab34d3c00e = []byte{
	// 1636 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x58, 0xcd, 0x6f, 0xdb, 0x46,
	0x16, 0x37, 0x25, 0x59, 0x96, 0xc6, 0xdf, 0xb4, 0xec, 0x28, 0xf6, 0x46, 0xd4, 0xce, 0x22, 0x1b,
	0x23, 0x89, 0x25, 0x59, 0xf6, 0x06, 0x5e, 0x5f, 0x16, 0xa4, 0xbd, 0x4e, 0x2c, 0xac, 0x13, 0x2f,
	0x63, 0xa0, 0x68, 0x3e, 0x40, 0xd0, 0xe4, 0x58, 0x26, 0x2c, 0x92, 0x32, 0x39, 0xb2, 0xa5, 0x14,
	0x29, 0x7a, 0xe8, 0x1f, 0x50, 0xe8, 0xd4, 0x5b, 0x53, 0x1f, 0x1a, 0xa0, 0x40, 0x4f, 0x05, 0x0a,
	0xf4, 0xde, 0x02, 0x39, 0x06, 0x28, 0x0a, 0x14, 0x3d, 0xa8, 0x6d, 0x72, 0x29, 0x0a, 0xb4, 0x07,
	0xfd, 0x05, 0xc5, 0x0c, 0x3f, 0x44, 0xc9, 0xb4, 0x13, 0xa7, 0x3e, 0xc6, 0x17, 0x91, 0x33, 0xef,
	0xfd, 0xde, 0x6f, 0xde, 0xfb, 0xbd, 0xc7, 0x81, 0xc1, 0x68, 0x45, 0xdb, 0xaf, 0x69, 0xaa, 0x86,
	0x1b, 0xb9, 0xaa, 0x65, 0x62, 0x93, 0x4d, 0x61, 0x64, 0xa8, 0xc8, 0xd2, 0x35, 0x03, 0xe7, 0xfc,
	0xbd, 0xe9, 0x04, 0xae, 0x3b, 0xfb, 0xd3, 0xa9, 0xb2, 0x59, 0x36, 0xe9, 0x63, 0x9e, 0x3c, 0xb9,
	0xab, 0x17, 0x14, 0xd3, 0xd6, 0x4d, 0x5b, 0x72, 0x36, 0x14, 0x53, 0x33, 0xdc, 0x0d, 0xe7, 0x47,
	0x99, 0x2b, 0x23, 0x63, 0xce, 0xac, 0x22, 0x43, 0xae, 0x6a, 0x07, 0xc5, 0xbc, 0x59, 0xc5, 0x9a,
	0x69, 0xd8, 0x79, 0xd9, 0x30, 0x4c, 0x2c, 0xd3, 0x67, 0xc7, 0x10, 0x7e, 0x15, 0x05, 0xe3, 0xff,
	0xf3, 0xc2, 0x6e, 0x9a, 0x66, 0x65, 0xab, 0x51, 0x45, 0xec, 0x5d, 0x30, 0x5a, 0x35, 0xcd, 0x8a,
	0x84, 0x1b, 0x55, 0x24, 0x69, 0x86, 0x8a, 0xea, 0x69, 0x26, 0xcb, 0xcc, 0x0e, 0x0b, 0xd7, 0x9a,
	0xfc, 0x48, 0x29, 0x0a, 0xe7, 0xe1, 0x51, 0x24, 0x5e, 0xd3, 0x0c, 0xbc, 0x50, 0x6c, 0xb7, 0xb8,
	0xa9, 0x86, 0xac, 0x57, 0x96, 0x61, 0x8f, 0x07, 0x14, 0x87, 0xab, 0x2e, 0xde, 0x3a, 0x79, 0x67,
	0xd7, 0x40, 0xcc, 0x90, 0x75, 0x94, 0x8e, 0x64, 0x99, 0xd9, 0xa4, 0x50, 0x6c, 0xf2, 0xd9, 0x52,
	0x06, 0xae, 0x98, 0x86, 0x8d, 0x65, 0x03, 0x6f, 0x5a, 0xa6, 0x5a, 0x53, 0x70, 0x17, 0x15, 0xd8,
	0x6e, 0x71, 0x83, 0x0e, 0x36, 0x71, 0x84, 0x22, 0xf5, 0x67, 0x65, 0x90, 0xd2, 0x35, 0x43, 0xb2,
	0x90, 0x8d, 0xac, 0x03, 0x24, 0x91, 0xc3, 0x4b, 0x46, 0x4d, 0x4f, 0x47, 0x29, 0xc3, 0x82, 0xc3,
	0xb0, 0xd8, 0xc5, 0x70, 0xc6, 0x41, 0x09, 0x73, 0x83, 0xe2, 0xb8, 0xae, 0x19, 0xa2, 0xb3, 0xba,
	0x62, 0x6a, 0xc6, 0xed, 0x9a, 0x4e, 0x43, 0xc8, 0xf5, 0xe3, 0x21, 0x62, 0xaf, 0x0e, 0x11, 0xe2,
	0x46, 0x42, 0xc8, 0xf5, 0x9e, 0x10, 0x4b, 0x60, 0x50, 0x45, 0xb6, 0x62, 0x69, 0xb4, 0x34, 0xe9,
	0x7e, 0x9a, 0x94, 0xa9, 0x76, 0x8b, 0x63, 0x1d, 0xa0, 0xc0, 0x26, 0x14, 0x83, 0xa6, 0xcb, 0xb1,
	0x5f, 0x9f, 0x70, 0x0c, 0xfc, 0x2e, 0x0e, 0xe2, 0x9b, 0xb2, 0x25, 0xeb, 0x36, 0xfb, 0x3e, 0x48,
	0xf9, 0xca, 0x91, 0xfc, 0x2a, 0xd8, 0x69, 0x26, 0x1b, 0x9d, 0x1d, 0x2c, 0x5e, 0xc9, 0x85, 0x29,
	0x2c, 0x77, 0xac, 0xe8, 0xc2, 0x3f, 0x9e, 0xb5, 0xb8, 0xbe, 0xce, 0x49, 0xc2, 0x20, 0xa1, 0xc8,
	0x56, 0x7a, 0xfd, 0x6c, 0xf6, 0x53, 0x06, 0xa4, 0x49, 0x6a, 0x35, 0x43, 0xc3, 0x92, 0x8a, 0xaa,
	0xa6, 0xad, 0x61, 0x09, 0x9b, 0xd4, 0xcf, 0xad, 0xb6, 0xd6, 0xe4, 0x27, 0x4b, 0x49, 0x38, 0x5f,
	0xa0, 0x7f, 0xf0, 0x28, 0x32, 0x60, 0xab, 0x7b, 0xb9, 0x75, 0x03, 0x93, 0x98, 0x3f, 0xb6, 0xb8,
	0x7f, 0x96, 0x35, 0xbc, 0x5b, 0xdb, 0xce, 0x29, 0xa6, 0x9e, 0x77, 0xa4, 0xed, 0xfe, 0xcc, 0xd9,
	0xea, 0x5e, 0x9e, 0xc6, 0x26, 0xd6, 0xed, 0x16, 0xc7, 0x75, 0x4a, 0x19, 0x16, 0x0f, 0x8a, 0x44,
	0x1c, 0xeb, 0x86, 0x86, 0x57, 0x9d, 0x8d, 0x2d, 0x93, 0x10, 0x65, 0x9f, 0x32, 0x60, 0x9a, 0xda,
	0xd3, 0xc3, 0xd0, 0xca, 0x90, 0x84, 0x48, 0xb2, 0x6e, 0xd6, 0x0c, 0x4c, 0xb5, 0x93, 0x14, 0xf6,
	0xce, 0x8d, 0xe5, 0xdf, 0x1d, 0x96, 0x27, 0x47, 0x84, 0xe2, 0x14, 0xd9, 0x24, 0xdc, 0x88, 0x22,
	0x36, 0x34, 0x03, 0xf3, 0x74, 0x83, 0xfd, 0x80, 0x01, 0xc3, 0xf6, 0xa1, 0x5c, 0x95, 0x76, 0x10,
	0x92, 0x2c, 0x19, 0x23, 0xaa, 0xba, 0x21, 0xe1, 0x41, 0x93, 0x9f, 0x28, 0x0d, 0xc0, 0x42, 0xae,
	0x50, 0x58, 0xf0, 0xa8, 0xad, 0x22, 0xe5, 0x0c, 0xd4, 0x56, 0x91, 0xd2, 0x6e, 0x71, 0x29, 0x87,
	0x5a, 0x57, 0x08, 0x28, 0x0e, 0x92, 0xf7, 0x35, 0x84, 0x44, 0x19, 0x23, 0xf6, 0x77, 0x06, 0xcc,
	0xf4, 0x94, 0x5f, 0xb1, 0x10, 0x9d, 0x1b, 0xc4, 0x25, 0xdd, 0x4f, 0x85, 0x75, 0x31, 0xe7, 0x44,
	0xc8, 0x6d, 0xcb, 0x36, 0xca, 0x1d, 0xcc, 0x6f, 0x23, 0x2c, 0xcf, 0xe7, 0xc8, 0x69, 0x84, 0x26,
	0xd3, 0xe4, 0xff, 0x5d, 0xba, 0x76, 0xff, 0x3d, 0xa8, 0x22, 0xc3, 0xd4, 0xe1, 0x72, 0x16, 0xd6,
	0x64, 0x6c, 0xea, 0xf0, 0x7a, 0x16, 0xba, 0xe7, 0x5f, 0xce, 0x7a, 0x79, 0x2e, 0x14, 0xe0, 0xe3,
	0x87, 0x47, 0x91, 0x24, 0x39, 0x10, 0xf1, 0xb6, 0x5d, 0x1d, 0xc2, 0x50, 0x1d, 0x06, 0x89, 0xc0,
	0xcf, 0x7f, 0xe2, 0x66, 0x5f, 0xe3, 0xe0, 0x14, 0x55, 0x4c, 0x77, 0x49, 0x77, 0xc5, 0xc5, 0x59,
	0x43, 0x68, 0x39, 0xf1, 0xf1, 0x13, 0xae, 0x8f, 0x76, 0xd5, 0xd7, 0x31, 0x30, 0xdc, 0xd5, 0x19,
	0xec, 0x4d, 0x30, 0x40, 0xe3, 0x6a, 0x2a, 0x1d, 0x81, 0x31, 0x21, 0xd7, 0x33, 0x02, 0x6f, 0x2c,
	0xfe, 0xd6, 0xe2, 0x3c, 0x9b, 0x76, 0x8b, 0x1b, 0x09, 0x4c, 0x43, 0x4d, 0x85, 0x62, 0x9c, 0x3c,
	0xad, 0xab, 0x61, 0x33, 0x35, 0xf2, 0x97, 0x67, 0xea, 0x0e, 0x98, 0xe8, 0x9a, 0x36, 0x34, 0xdd,
	0x76, 0x3a, 0x9a, 0x8d, 0xce, 0x26, 0x85, 0x1b, 0x44, 0xce, 0x13, 0xf7, 0x9d, 0x1a, 0xf0, 0xf0,
	0xba, 0xf3, 0x20, 0xc0, 0x87, 0xed, 0x16, 0x37, 0xed, 0xe0, 0x87, 0x38, 0x43, 0x71, 0xdc, 0xea,
	0x8c, 0xaa, 0x55, 0xba, 0xc6, 0x7e, 0xc2, 0x80, 0x0b, 0x9e, 0xad, 0xac, 0x28, 0xa4, 0x82, 0x92,
	0xac, 0xaa, 0x16, 0xb2, 0x6d, 0x2a, 0xcf, 0xa4, 0x50, 0x6e, 0xf2, 0x42, 0x29, 0x0f, 0x9d, 0xdc,
	0xcf, 0xef, 0x3f, 0x5a, 0x58, 0x32, 0x1a, 0xfa, 0x9e, 0x8d, 0xf0, 0xbe, 0x5a, 0x54, 0x17, 0xf7,
	0x91, 0x6d, 0xd5, 0xab, 0x3b, 0x3b, 0x8f, 0x1a, 0x87, 0x35, 0x54, 0x59, 0x2a, 0xca, 0x8b, 0x95,
	0xc2, 0x81, 0x0d, 0x8f, 0x22, 0x23, 0xa4, 0xea, 0xbc, 0xa2, 0xf0, 0x0e, 0x58, 0xbb, 0xc5, 0x65,
	0xba, 0x99, 0xf5, 0x44, 0x83, 0xe2, 0xa4, 0xbb, 0xc3, 0x3b, 0x1b, 0xae, 0x23, 0x7b, 0xe0, 0xa6,
	0xb7, 0x73, 0x12, 0x77, 0xa6, 0xde, 0x6e, 0xf2, 0xf3, 0x67, 0x26, 0xd6, 0x53, 0x81, 0x0e, 0xa8,
	0x5b, 0x01, 0x3f, 0x35, 0x54, 0x3b, 0x0c, 0xd5, 0xce, 0x97, 0x31, 0x30, 0xd9, 0xa5, 0x9d, 0x0d,
	0x84, 0x65, 0x55, 0xc6, 0xf2, 0xf9, 0x69, 0xe8, 0x7b, 0x06, 0x4c, 0x75, 0x08, 0x61, 0x13, 0xcb,
	0x15, 0xc9, 0xae, 0x55, 0xab, 0x95, 0x06, 0xd5, 0xd2, 0xa9, 0x3d, 0xf9, 0x21, 0xd3, 0xe4, 0x1f,
	0x94, 0xee, 0x04, 0x5a, 0xf2, 0x6c, 0x29, 0x09, 0x6b, 0x5d, 0xf8, 0xf8, 0x28, 0x92, 0xf0, 0xfa,
	0xd6, 0x6d, 0xdb, 0x4b, 0xbd, 0x79, 0x0b, 0xd2, 0x84, 0xe2, 0x84, 0x97, 0xbe, 0x2d, 0xb2, 0x7c,
	0x97, 0xae, 0xb2, 0x7f, 0x30, 0x60, 0x38, 0x28, 0x45, 0x47, 0xc1, 0xa7, 0x1e, 0xe7, 0x0b, 0xa6,
	0xc9, 0x6f, 0x97, 0xb6, 0x82, 0x23, 0xc6, 0xd3, 0x79, 0x28, 0xd1, 0xeb, 0xd9, 0x5e, 0x4b, 0xa1,
	0xdb, 0xb2, 0x78, 0xda, 0x2c, 0x4a, 0x1d, 0x6f, 0x17, 0xfb, 0x6c, 0xd3, 0x67, 0x28, 0xd0, 0x54,
	0x76, 0x40, 0x35, 0xdf, 0xc6, 0x00, 0xdb, 0xa5, 0x1a, 0x41, 0xc6, 0xca, 0xee, 0xf9, 0x49, 0xe6,
	0x16, 0x18, 0xdc, 0x26, 0x88, 0x81, 0x91, 0x13, 0x13, 0xae, 0x1c, 0x03, 0xeb, 0x5c, 0x3c, 0x02,
	0xd6, 0x50, 0x04, 0xf4, 0xcd, 0x99, 0x35, 0x1b, 0x60, 0x68, 0x1b, 0x95, 0x35, 0x43, 0xda, 0x45,
	0x5a, 0x79, 0xd7, 0xf9, 0x66, 0x46, 0x85, 0xab, 0x4d, 0x7e, 0xac, 0x14, 0xa7, 0x79, 0x86, 0x47,
	0x91, 0x7e, 0x0f, 0x6c, 0xc2, 0x05, 0x0b, 0x38, 0x40, 0x71, 0x90, 0xbe, 0xde, 0xa2, 0x6f, 0xec,
	0xbb, 0x60, 0xdc, 0xfb, 0x76, 0xeb, 0x76, 0xd9, 0xa5, 0x17, 0xa3, 0xf4, 0xe6, 0xc2, 0xe8, 0xa5,
	0xbd, 0x7b, 0x51, 0x8f, 0x0f, 0x14, 0x47, 0xdd, 0xb5, 0x0d, 0xbb, 0xec, 0x30, 0x7d, 0x00, 0xd8,
	0x43, 0x0d, 0xef, 0xaa, 0x96, 0x7c, 0x18, 0xc0, 0xee, 0x3f, 0x21, 0x8f, 0xed, 0x16, 0x77, 0xd1,
	0xc1, 0x3e, 0xee, 0x04, 0xc5, 0x31, 0x6f, 0xd1, 0x47, 0xdf, 0x04, 0x23, 0xf4, 0xe3, 0xd9, 0x41,
	0x8e, 0x53, 0xe4, 0xab, 0x61, 0xc8, 0x93, 0x81, 0xaf, 0x6d, 0x00, 0x75, 0x88, 0x2c, 0xf8, 0x88,
	0x4b, 0x20, 0x81, 0xea, 0x48, 0xa9, 0x61, 0xa4, 0xa6, 0x07, 0xb2, 0xcc, 0x6c, 0x42, 0xf8, 0x5b,
	0x93, 0x8f, 0x97, 0x62, 0xd8, 0xaa, 0xa1, 0x76, 0x8b, 0x1b, 0x75, 0x30, 0x3c, 0x13, 0x28, 0xfa,
	0xd6, 0x01, 0x1d, 0x1d, 0x45, 0xc1, 0x04, 0x95, 0x0e, 0xd1, 0xd0, 0xaa, 0x9f, 0x10, 0xf6, 0x26,
	0x00, 0x24, 0xae, 0x5b, 0x33, 0x86, 0xd6, 0x6c, 0x36, 0xbc, 0x66, 0xe3, 0xee, 0xd5, 0xca, 0x37,
	0x87, 0x62, 0x52, 0xb7, 0xcb, 0x6e, 0xbd, 0x04, 0x90, 0xec, 0x9c, 0xd8, 0x91, 0xd1, 0xe5, 0xb0,
	0x13, 0x8f, 0x75, 0x50, 0xdc, 0xc3, 0x26, 0xf4, 0xb0, 0x83, 0x46, 0xcf, 0x72, 0x50, 0xf6, 0x5f,
	0x60, 0xc0, 0xae, 0x29, 0x0a, 0x42, 0x2a, 0xd5, 0x48, 0x42, 0x98, 0x09, 0x3a, 0xba, 0xe2, 0x77,
	0x2d, 0xa0, 0xe8, 0xd9, 0xb2, 0xcb, 0x20, 0x89, 0x4d, 0x49, 0x45, 0x15, 0x84, 0x11, 0x15, 0x40,
	0x42, 0xb8, 0x14, 0x74, 0x74, 0xc9, 0xfa, 0x36, 0x50, 0x4c, 0x60, 0x73, 0x95, 0x3e, 0xb2, 0xff,
	0x07, 0x51, 0xdd, 0x2e, 0xd3, 0xe2, 0x0e, 0x16, 0xf3, 0xe1, 0xb7, 0xe8, 0x0d, 0xbb, 0xec, 0xdf,
	0x33, 0xbb, 0xbb, 0x78, 0xa4, 0xdd, 0xe2, 0x80, 0x9f, 0x0a, 0x28, 0x12, 0x2c, 0xf8, 0x59, 0x14,
	0xa4, 0xfc, 0x22, 0xbd, 0xd3, 0x11, 0xd6, 0xdb, 0x2a, 0xbd, 0x71, 0x95, 0xb6, 0x82, 0x55, 0x2a,
	0x9e, 0x58, 0x25, 0x2f, 0xd9, 0x6b, 0x96, 0xa9, 0xbf, 0x46, 0xa1, 0xbe, 0x89, 0x83, 0x31, 0xbf,
	0x50, 0x77, 0x9d, 0x5e, 0x7d, 0x5b, 0xa4, 0x37, 0x2e, 0x92, 0x0c, 0x26, 0x4c, 0x4b, 0x45, 0x96,
	0x84, 0xea, 0x55, 0xcd, 0x6a, 0x78, 0x29, 0x8c, 0xd3, 0x14, 0xce, 0x87, 0xa7, 0xd0, 0xbd, 0xa1,
	0x86, 0xf8, 0x41, 0x71, 0x9c, 0xae, 0xfe, 0x97, 0x2e, 0xba, 0x39, 0x7d, 0xca, 0x80, 0x14, 0xaa,
	0x2b, 0xbb, 0xb2, 0x51, 0x46, 0xaa, 0x64, 0xee, 0xec, 0x20, 0x8b, 0x7e, 0xa6, 0xe9, 0x40, 0x3d,
	0xf5, 0x26, 0x71, 0xaf, 0xc9, 0x2f, 0x96, 0xae, 0xbc, 0xe2, 0x1e, 0x71, 0xe3, 0xc4, 0xfb, 0xce,
	0x8c, 0x97, 0xe9, 0xe3, 0xb1, 0xa1, 0xc8, 0xfa, 0xcb, 0x77, 0xc8, 0x2a, 0x71, 0xa3, 0x4c, 0x2d,
	0xa4, 0xcb, 0x9a, 0xa1, 0x19, 0xe5, 0x20, 0xd3, 0xc4, 0xb9, 0x30, 0x5d, 0x7c, 0x15, 0xd3, 0xb0,
	0xd8, 0x50, 0x64, 0xfd, 0xe5, 0x0e, 0xd3, 0xff, 0x38, 0xbd, 0x95, 0xa4, 0xbc, 0x2e, 0x9d, 0xd8,
	0x5b, 0xa4, 0x3f, 0x42, 0xdb, 0x48, 0x58, 0x79, 0xf6, 0x4b, 0xa6, 0xef, 0xd9, 0x8b, 0x0c, 0xf3,
	0xfc, 0x45, 0x86, 0xf9, 0xf9, 0x45, 0x86, 0xf9, 0xe8, 0x65, 0xa6, 0xef, 0xf9, 0xcb, 0x4c, 0xdf,
	0x0f, 0x2f, 0x33, 0x7d, 0xf7, 0x2e, 0x07, 0x2e, 0x4f, 0x1d, 0xec, 0xbc, 0x8f, 0xed, 0xdc, 0x9f,
	0xb6, 0xe3, 0xf4, 0x3f, 0x55, 0x0b, 0x7f, 0x06, 0x00, 0x00, 0xff, 0xff, 0x76, 0xfd, 0xd7, 0x41,
	0x3b, 0x13, 0x00, 0x00,
}

func (this *LiquidityPoolType) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*LiquidityPoolType)
	if !ok {
		that2, ok := that.(LiquidityPoolType)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.PoolTypeIndex != that1.PoolTypeIndex {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.MinReserveCoinNum != that1.MinReserveCoinNum {
		return false
	}
	if this.MaxReserveCoinNum != that1.MaxReserveCoinNum {
		return false
	}
	if this.Description != that1.Description {
		return false
	}
	return true
}
func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.LiquidityPoolTypes) != len(that1.LiquidityPoolTypes) {
		return false
	}
	for i := range this.LiquidityPoolTypes {
		if !this.LiquidityPoolTypes[i].Equal(&that1.LiquidityPoolTypes[i]) {
			return false
		}
	}
	if !this.MinInitDepositToPool.Equal(that1.MinInitDepositToPool) {
		return false
	}
	if !this.InitPoolCoinMintAmount.Equal(that1.InitPoolCoinMintAmount) {
		return false
	}
	if !this.SwapFeeRate.Equal(that1.SwapFeeRate) {
		return false
	}
	if len(this.LiquidityPoolCreationFee) != len(that1.LiquidityPoolCreationFee) {
		return false
	}
	for i := range this.LiquidityPoolCreationFee {
		if !this.LiquidityPoolCreationFee[i].Equal(&that1.LiquidityPoolCreationFee[i]) {
			return false
		}
	}
	return true
}
func (this *LiquidityPool) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*LiquidityPool)
	if !ok {
		that2, ok := that.(LiquidityPool)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.PoolId != that1.PoolId {
		return false
	}
	if this.PoolTypeIndex != that1.PoolTypeIndex {
		return false
	}
	if len(this.ReserveCoinDenoms) != len(that1.ReserveCoinDenoms) {
		return false
	}
	for i := range this.ReserveCoinDenoms {
		if this.ReserveCoinDenoms[i] != that1.ReserveCoinDenoms[i] {
			return false
		}
	}
	if this.ReserveAccountAddress != that1.ReserveAccountAddress {
		return false
	}
	if this.PoolCoinDenom != that1.PoolCoinDenom {
		return false
	}
	return true
}
func (this *LiquidityPoolMetadata) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*LiquidityPoolMetadata)
	if !ok {
		that2, ok := that.(LiquidityPoolMetadata)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.PoolId != that1.PoolId {
		return false
	}
	if !this.PoolCoinTotalSupply.Equal(&that1.PoolCoinTotalSupply) {
		return false
	}
	if len(this.ReserveCoins) != len(that1.ReserveCoins) {
		return false
	}
	for i := range this.ReserveCoins {
		if !this.ReserveCoins[i].Equal(&that1.ReserveCoins[i]) {
			return false
		}
	}
	return true
}
func (this *LiquidityPoolBatch) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*LiquidityPoolBatch)
	if !ok {
		that2, ok := that.(LiquidityPoolBatch)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.PoolId != that1.PoolId {
		return false
	}
	if this.BatchIndex != that1.BatchIndex {
		return false
	}
	if this.BeginHeight != that1.BeginHeight {
		return false
	}
	if this.DepositMsgIndex != that1.DepositMsgIndex {
		return false
	}
	if this.WithdrawMsgIndex != that1.WithdrawMsgIndex {
		return false
	}
	if this.SwapMsgIndex != that1.SwapMsgIndex {
		return false
	}
	if this.Executed != that1.Executed {
		return false
	}
	return true
}
func (m *LiquidityPoolType) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LiquidityPoolType) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LiquidityPoolType) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintLiquidity(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x2a
	}
	if m.MaxReserveCoinNum != 0 {
		i = encodeVarintLiquidity(dAtA, i, uint64(m.MaxReserveCoinNum))
		i--
		dAtA[i] = 0x20
	}
	if m.MinReserveCoinNum != 0 {
		i = encodeVarintLiquidity(dAtA, i, uint64(m.MinReserveCoinNum))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintLiquidity(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if m.PoolTypeIndex != 0 {
		i = encodeVarintLiquidity(dAtA, i, uint64(m.PoolTypeIndex))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.LiquidityPoolCreationFee) > 0 {
		for iNdEx := len(m.LiquidityPoolCreationFee) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.LiquidityPoolCreationFee[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintLiquidity(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	{
		size := m.SwapFeeRate.Size()
		i -= size
		if _, err := m.SwapFeeRate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLiquidity(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.InitPoolCoinMintAmount.Size()
		i -= size
		if _, err := m.InitPoolCoinMintAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLiquidity(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.MinInitDepositToPool.Size()
		i -= size
		if _, err := m.MinInitDepositToPool.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLiquidity(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.LiquidityPoolTypes) > 0 {
		for iNdEx := len(m.LiquidityPoolTypes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.LiquidityPoolTypes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintLiquidity(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *LiquidityPool) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LiquidityPool) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LiquidityPool) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PoolCoinDenom) > 0 {
		i -= len(m.PoolCoinDenom)
		copy(dAtA[i:], m.PoolCoinDenom)
		i = encodeVarintLiquidity(dAtA, i, uint64(len(m.PoolCoinDenom)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ReserveAccountAddress) > 0 {
		i -= len(m.ReserveAccountAddress)
		copy(dAtA[i:], m.ReserveAccountAddress)
		i = encodeVarintLiquidity(dAtA, i, uint64(len(m.ReserveAccountAddress)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ReserveCoinDenoms) > 0 {
		for iNdEx := len(m.ReserveCoinDenoms) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.ReserveCoinDenoms[iNdEx])
			copy(dAtA[i:], m.ReserveCoinDenoms[iNdEx])
			i = encodeVarintLiquidity(dAtA, i, uint64(len(m.ReserveCoinDenoms[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.PoolTypeIndex != 0 {
		i = encodeVarintLiquidity(dAtA, i, uint64(m.PoolTypeIndex))
		i--
		dAtA[i] = 0x10
	}
	if m.PoolId != 0 {
		i = encodeVarintLiquidity(dAtA, i, uint64(m.PoolId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *LiquidityPoolMetadata) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LiquidityPoolMetadata) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LiquidityPoolMetadata) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ReserveCoins) > 0 {
		for iNdEx := len(m.ReserveCoins) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ReserveCoins[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintLiquidity(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	{
		size, err := m.PoolCoinTotalSupply.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintLiquidity(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.PoolId != 0 {
		i = encodeVarintLiquidity(dAtA, i, uint64(m.PoolId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *LiquidityPoolBatch) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LiquidityPoolBatch) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LiquidityPoolBatch) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Executed {
		i--
		if m.Executed {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if m.SwapMsgIndex != 0 {
		i = encodeVarintLiquidity(dAtA, i, uint64(m.SwapMsgIndex))
		i--
		dAtA[i] = 0x30
	}
	if m.WithdrawMsgIndex != 0 {
		i = encodeVarintLiquidity(dAtA, i, uint64(m.WithdrawMsgIndex))
		i--
		dAtA[i] = 0x28
	}
	if m.DepositMsgIndex != 0 {
		i = encodeVarintLiquidity(dAtA, i, uint64(m.DepositMsgIndex))
		i--
		dAtA[i] = 0x20
	}
	if m.BeginHeight != 0 {
		i = encodeVarintLiquidity(dAtA, i, uint64(m.BeginHeight))
		i--
		dAtA[i] = 0x18
	}
	if m.BatchIndex != 0 {
		i = encodeVarintLiquidity(dAtA, i, uint64(m.BatchIndex))
		i--
		dAtA[i] = 0x10
	}
	if m.PoolId != 0 {
		i = encodeVarintLiquidity(dAtA, i, uint64(m.PoolId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *BatchPoolDepositMsg) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BatchPoolDepositMsg) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BatchPoolDepositMsg) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Msg != nil {
		{
			size, err := m.Msg.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintLiquidity(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	if m.ToDelete {
		i--
		if m.ToDelete {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if m.Succeed {
		i--
		if m.Succeed {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if m.Executed {
		i--
		if m.Executed {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.MsgIndex != 0 {
		i = encodeVarintLiquidity(dAtA, i, uint64(m.MsgIndex))
		i--
		dAtA[i] = 0x10
	}
	if m.MsgHeight != 0 {
		i = encodeVarintLiquidity(dAtA, i, uint64(m.MsgHeight))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *BatchPoolWithdrawMsg) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BatchPoolWithdrawMsg) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BatchPoolWithdrawMsg) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Msg != nil {
		{
			size, err := m.Msg.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintLiquidity(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	if m.ToDelete {
		i--
		if m.ToDelete {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if m.Succeed {
		i--
		if m.Succeed {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if m.Executed {
		i--
		if m.Executed {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.MsgIndex != 0 {
		i = encodeVarintLiquidity(dAtA, i, uint64(m.MsgIndex))
		i--
		dAtA[i] = 0x10
	}
	if m.MsgHeight != 0 {
		i = encodeVarintLiquidity(dAtA, i, uint64(m.MsgHeight))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *BatchPoolSwapMsg) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BatchPoolSwapMsg) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BatchPoolSwapMsg) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Msg != nil {
		{
			size, err := m.Msg.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintLiquidity(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x4a
	}
	{
		size, err := m.RemainingOfferCoin.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintLiquidity(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	{
		size, err := m.ExchangedOfferCoin.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintLiquidity(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	if m.OrderExpiryHeight != 0 {
		i = encodeVarintLiquidity(dAtA, i, uint64(m.OrderExpiryHeight))
		i--
		dAtA[i] = 0x30
	}
	if m.ToDelete {
		i--
		if m.ToDelete {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if m.Succeed {
		i--
		if m.Succeed {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if m.Executed {
		i--
		if m.Executed {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.MsgIndex != 0 {
		i = encodeVarintLiquidity(dAtA, i, uint64(m.MsgIndex))
		i--
		dAtA[i] = 0x10
	}
	if m.MsgHeight != 0 {
		i = encodeVarintLiquidity(dAtA, i, uint64(m.MsgHeight))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintLiquidity(dAtA []byte, offset int, v uint64) int {
	offset -= sovLiquidity(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *LiquidityPoolType) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PoolTypeIndex != 0 {
		n += 1 + sovLiquidity(uint64(m.PoolTypeIndex))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovLiquidity(uint64(l))
	}
	if m.MinReserveCoinNum != 0 {
		n += 1 + sovLiquidity(uint64(m.MinReserveCoinNum))
	}
	if m.MaxReserveCoinNum != 0 {
		n += 1 + sovLiquidity(uint64(m.MaxReserveCoinNum))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovLiquidity(uint64(l))
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.LiquidityPoolTypes) > 0 {
		for _, e := range m.LiquidityPoolTypes {
			l = e.Size()
			n += 1 + l + sovLiquidity(uint64(l))
		}
	}
	l = m.MinInitDepositToPool.Size()
	n += 1 + l + sovLiquidity(uint64(l))
	l = m.InitPoolCoinMintAmount.Size()
	n += 1 + l + sovLiquidity(uint64(l))
	l = m.SwapFeeRate.Size()
	n += 1 + l + sovLiquidity(uint64(l))
	if len(m.LiquidityPoolCreationFee) > 0 {
		for _, e := range m.LiquidityPoolCreationFee {
			l = e.Size()
			n += 1 + l + sovLiquidity(uint64(l))
		}
	}
	return n
}

func (m *LiquidityPool) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PoolId != 0 {
		n += 1 + sovLiquidity(uint64(m.PoolId))
	}
	if m.PoolTypeIndex != 0 {
		n += 1 + sovLiquidity(uint64(m.PoolTypeIndex))
	}
	if len(m.ReserveCoinDenoms) > 0 {
		for _, s := range m.ReserveCoinDenoms {
			l = len(s)
			n += 1 + l + sovLiquidity(uint64(l))
		}
	}
	l = len(m.ReserveAccountAddress)
	if l > 0 {
		n += 1 + l + sovLiquidity(uint64(l))
	}
	l = len(m.PoolCoinDenom)
	if l > 0 {
		n += 1 + l + sovLiquidity(uint64(l))
	}
	return n
}

func (m *LiquidityPoolMetadata) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PoolId != 0 {
		n += 1 + sovLiquidity(uint64(m.PoolId))
	}
	l = m.PoolCoinTotalSupply.Size()
	n += 1 + l + sovLiquidity(uint64(l))
	if len(m.ReserveCoins) > 0 {
		for _, e := range m.ReserveCoins {
			l = e.Size()
			n += 1 + l + sovLiquidity(uint64(l))
		}
	}
	return n
}

func (m *LiquidityPoolBatch) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PoolId != 0 {
		n += 1 + sovLiquidity(uint64(m.PoolId))
	}
	if m.BatchIndex != 0 {
		n += 1 + sovLiquidity(uint64(m.BatchIndex))
	}
	if m.BeginHeight != 0 {
		n += 1 + sovLiquidity(uint64(m.BeginHeight))
	}
	if m.DepositMsgIndex != 0 {
		n += 1 + sovLiquidity(uint64(m.DepositMsgIndex))
	}
	if m.WithdrawMsgIndex != 0 {
		n += 1 + sovLiquidity(uint64(m.WithdrawMsgIndex))
	}
	if m.SwapMsgIndex != 0 {
		n += 1 + sovLiquidity(uint64(m.SwapMsgIndex))
	}
	if m.Executed {
		n += 2
	}
	return n
}

func (m *BatchPoolDepositMsg) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MsgHeight != 0 {
		n += 1 + sovLiquidity(uint64(m.MsgHeight))
	}
	if m.MsgIndex != 0 {
		n += 1 + sovLiquidity(uint64(m.MsgIndex))
	}
	if m.Executed {
		n += 2
	}
	if m.Succeed {
		n += 2
	}
	if m.ToDelete {
		n += 2
	}
	if m.Msg != nil {
		l = m.Msg.Size()
		n += 1 + l + sovLiquidity(uint64(l))
	}
	return n
}

func (m *BatchPoolWithdrawMsg) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MsgHeight != 0 {
		n += 1 + sovLiquidity(uint64(m.MsgHeight))
	}
	if m.MsgIndex != 0 {
		n += 1 + sovLiquidity(uint64(m.MsgIndex))
	}
	if m.Executed {
		n += 2
	}
	if m.Succeed {
		n += 2
	}
	if m.ToDelete {
		n += 2
	}
	if m.Msg != nil {
		l = m.Msg.Size()
		n += 1 + l + sovLiquidity(uint64(l))
	}
	return n
}

func (m *BatchPoolSwapMsg) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MsgHeight != 0 {
		n += 1 + sovLiquidity(uint64(m.MsgHeight))
	}
	if m.MsgIndex != 0 {
		n += 1 + sovLiquidity(uint64(m.MsgIndex))
	}
	if m.Executed {
		n += 2
	}
	if m.Succeed {
		n += 2
	}
	if m.ToDelete {
		n += 2
	}
	if m.OrderExpiryHeight != 0 {
		n += 1 + sovLiquidity(uint64(m.OrderExpiryHeight))
	}
	l = m.ExchangedOfferCoin.Size()
	n += 1 + l + sovLiquidity(uint64(l))
	l = m.RemainingOfferCoin.Size()
	n += 1 + l + sovLiquidity(uint64(l))
	if m.Msg != nil {
		l = m.Msg.Size()
		n += 1 + l + sovLiquidity(uint64(l))
	}
	return n
}

func sovLiquidity(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozLiquidity(x uint64) (n int) {
	return sovLiquidity(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *LiquidityPoolType) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLiquidity
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LiquidityPoolType: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LiquidityPoolType: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolTypeIndex", wireType)
			}
			m.PoolTypeIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PoolTypeIndex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinReserveCoinNum", wireType)
			}
			m.MinReserveCoinNum = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinReserveCoinNum |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxReserveCoinNum", wireType)
			}
			m.MaxReserveCoinNum = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxReserveCoinNum |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLiquidity(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthLiquidity
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthLiquidity
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLiquidity
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidityPoolTypes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLiquidity
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LiquidityPoolTypes = append(m.LiquidityPoolTypes, LiquidityPoolType{})
			if err := m.LiquidityPoolTypes[len(m.LiquidityPoolTypes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinInitDepositToPool", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinInitDepositToPool.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitPoolCoinMintAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.InitPoolCoinMintAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SwapFeeRate", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthLiquidity
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SwapFeeRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidityPoolCreationFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLiquidity
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LiquidityPoolCreationFee = append(m.LiquidityPoolCreationFee, types.Coin{})
			if err := m.LiquidityPoolCreationFee[len(m.LiquidityPoolCreationFee)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLiquidity(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthLiquidity
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthLiquidity
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LiquidityPool) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLiquidity
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LiquidityPool: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LiquidityPool: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolId", wireType)
			}
			m.PoolId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PoolId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolTypeIndex", wireType)
			}
			m.PoolTypeIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PoolTypeIndex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReserveCoinDenoms", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReserveCoinDenoms = append(m.ReserveCoinDenoms, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReserveAccountAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReserveAccountAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolCoinDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PoolCoinDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLiquidity(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthLiquidity
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthLiquidity
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LiquidityPoolMetadata) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLiquidity
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LiquidityPoolMetadata: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LiquidityPoolMetadata: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolId", wireType)
			}
			m.PoolId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PoolId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolCoinTotalSupply", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLiquidity
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PoolCoinTotalSupply.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReserveCoins", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLiquidity
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReserveCoins = append(m.ReserveCoins, types.Coin{})
			if err := m.ReserveCoins[len(m.ReserveCoins)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLiquidity(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthLiquidity
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthLiquidity
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LiquidityPoolBatch) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLiquidity
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LiquidityPoolBatch: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LiquidityPoolBatch: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolId", wireType)
			}
			m.PoolId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PoolId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BatchIndex", wireType)
			}
			m.BatchIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BatchIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BeginHeight", wireType)
			}
			m.BeginHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BeginHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositMsgIndex", wireType)
			}
			m.DepositMsgIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DepositMsgIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithdrawMsgIndex", wireType)
			}
			m.WithdrawMsgIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WithdrawMsgIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SwapMsgIndex", wireType)
			}
			m.SwapMsgIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SwapMsgIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Executed", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Executed = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipLiquidity(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthLiquidity
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthLiquidity
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BatchPoolDepositMsg) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLiquidity
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BatchPoolDepositMsg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BatchPoolDepositMsg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgHeight", wireType)
			}
			m.MsgHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MsgHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgIndex", wireType)
			}
			m.MsgIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MsgIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Executed", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Executed = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Succeed", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Succeed = bool(v != 0)
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ToDelete", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ToDelete = bool(v != 0)
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msg", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLiquidity
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Msg == nil {
				m.Msg = &MsgDepositToLiquidityPool{}
			}
			if err := m.Msg.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLiquidity(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthLiquidity
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthLiquidity
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BatchPoolWithdrawMsg) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLiquidity
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BatchPoolWithdrawMsg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BatchPoolWithdrawMsg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgHeight", wireType)
			}
			m.MsgHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MsgHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgIndex", wireType)
			}
			m.MsgIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MsgIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Executed", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Executed = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Succeed", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Succeed = bool(v != 0)
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ToDelete", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ToDelete = bool(v != 0)
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msg", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLiquidity
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Msg == nil {
				m.Msg = &MsgWithdrawFromLiquidityPool{}
			}
			if err := m.Msg.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLiquidity(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthLiquidity
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthLiquidity
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BatchPoolSwapMsg) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLiquidity
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BatchPoolSwapMsg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BatchPoolSwapMsg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgHeight", wireType)
			}
			m.MsgHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MsgHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgIndex", wireType)
			}
			m.MsgIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MsgIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Executed", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Executed = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Succeed", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Succeed = bool(v != 0)
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ToDelete", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ToDelete = bool(v != 0)
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrderExpiryHeight", wireType)
			}
			m.OrderExpiryHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OrderExpiryHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExchangedOfferCoin", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLiquidity
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ExchangedOfferCoin.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemainingOfferCoin", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLiquidity
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RemainingOfferCoin.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msg", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLiquidity
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Msg == nil {
				m.Msg = &MsgSwap{}
			}
			if err := m.Msg.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLiquidity(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthLiquidity
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthLiquidity
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipLiquidity(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowLiquidity
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLiquidity
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLiquidity
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthLiquidity
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupLiquidity
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthLiquidity
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthLiquidity        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowLiquidity          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupLiquidity = fmt.Errorf("proto: unexpected end of group")
)
