// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: msg.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899) }

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 621 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x96, 0x4f, 0x6b, 0x13, 0x5d,
	0x14, 0x87, 0x9b, 0x36, 0xf4, 0x7d, 0xdf, 0x59, 0xbd, 0x06, 0x15, 0x0c, 0x25, 0x1c, 0x82, 0x15,
	0xac, 0x69, 0x2e, 0xb4, 0xa2, 0xd8, 0x8d, 0xd4, 0x3f, 0x5d, 0x59, 0x2c, 0xb6, 0x20, 0xb8, 0x91,
	0x9b, 0xb9, 0xa7, 0x33, 0x17, 0x26, 0xf7, 0xdc, 0xde, 0x7b, 0xa6, 0x49, 0x51, 0x41, 0x04, 0xf7,
	0x62, 0xbf, 0x82, 0x2b, 0x3f, 0x82, 0xa0, 0x6b, 0x17, 0x2e, 0x0a, 0x82, 0xb8, 0x94, 0xd6, 0x6f,
	0xe0, 0x17, 0x90, 0xc9, 0x64, 0xda, 0x60, 0x13, 0x42, 0x5d, 0x75, 0xd1, 0xd5, 0x1d, 0xe6, 0x9c,
	0xe7, 0x77, 0x0f, 0x73, 0x9e, 0xc5, 0x04, 0xff, 0xb5, 0x7d, 0xd4, 0xb4, 0x8e, 0x98, 0x2a, 0xe7,
	0x19, 0x8d, 0x42, 0xd7, 0xd6, 0x86, 0x9b, 0x89, 0xde, 0x4a, 0xb5, 0xd2, 0xbc, 0x53, 0x9d, 0x89,
	0x88, 0xa2, 0x04, 0x85, 0xb4, 0x5a, 0x48, 0x63, 0x88, 0x25, 0x6b, 0x32, 0x3e, 0x67, 0xaa, 0xf9,
	0x11, 0xce, 0x47, 0x68, 0xe6, 0xc9, 0xa2, 0x91, 0x56, 0x6f, 0x2f, 0x08, 0xb2, 0xbd, 0x9e, 0x21,
	0xfd, 0xff, 0x72, 0x37, 0x7f, 0x5a, 0xf8, 0x75, 0x2e, 0x98, 0x5e, 0xf5, 0xd1, 0xb2, 0xd5, 0x95,
	0xf7, 0xe5, 0xe0, 0xe2, 0x5d, 0x87, 0x92, 0xf1, 0x41, 0x71, 0xed, 0x1a, 0x51, 0x92, 0x95, 0x16,
	0x9b, 0xc3, 0x86, 0x6a, 0xae, 0xfa, 0x68, 0x08, 0xf0, 0x08, 0xb7, 0x52, 0xf4, 0x5c, 0xbd, 0x7e,
	0x32, 0xc8, 0x5b, 0x32, 0x1e, 0xeb, 0xef, 0xa6, 0xde, 0x2e, 0xbf, 0x9e, 0x0a, 0x26, 0x37, 0xba,
	0xd5, 0x97, 0x93, 0xa9, 0xf1, 0x3a, 0x32, 0xa8, 0x80, 0xbb, 0x10, 0x4a, 0x03, 0x2d, 0x84, 0x08,
	0x0d, 0x3a, 0xc9, 0xa8, 0x20, 0xb5, 0x64, 0xc0, 0xe5, 0x97, 0x01, 0xc7, 0x8e, 0xd2, 0x28, 0x06,
	0x8e, 0xb5, 0x87, 0xb5, 0x87, 0xeb, 0x1b, 0x80, 0x46, 0x59, 0xd2, 0x86, 0x1b, 0xb0, 0x43, 0x69,
	0x4e, 0x3b, 0x92, 0x2a, 0x94, 0x9e, 0x41, 0x2a, 0xa5, 0x4d, 0x04, 0x59, 0xb8, 0xe4, 0xd4, 0x21,
	0x30, 0x01, 0xc7, 0x83, 0xe1, 0xdc, 0x6d, 0x1c, 0x66, 0x16, 0x49, 0xe0, 0xd3, 0x30, 0x06, 0xe9,
	0x41, 0x70, 0xd7, 0x03, 0x39, 0x70, 0x36, 0x6c, 0xc0, 0xf2, 0x26, 0xa3, 0x3b, 0xca, 0x6e, 0xf4,
	0x82, 0x1c, 0xfa, 0x34, 0xe1, 0x62, 0x66, 0x9f, 0xb6, 0x7c, 0xe8, 0x74, 0x0b, 0x07, 0xc6, 0x44,
	0xc0, 0x6d, 0x34, 0x0c, 0xd2, 0x28, 0xb0, 0x09, 0x4a, 0x9f, 0x41, 0x9b, 0xe8, 0x8a, 0x51, 0xbc,
	0xc5, 0xb0, 0x59, 0x7f, 0x1e, 0x2c, 0xae, 0x68, 0xa3, 0x80, 0x52, 0x86, 0x36, 0x39, 0x84, 0x36,
	0x7a, 0x2f, 0xa3, 0xbc, 0xdc, 0x63, 0x5d, 0xff, 0xc3, 0xe5, 0x71, 0x1e, 0x62, 0x74, 0x58, 0xb9,
	0x1f, 0x33, 0x5b, 0xbf, 0x24, 0x44, 0xa4, 0x39, 0x4e, 0x5b, 0xcd, 0x90, 0xda, 0xe2, 0x68, 0x19,
	0xe2, 0x70, 0x19, 0x82, 0x1d, 0xa2, 0x50, 0xb8, 0x8d, 0x09, 0x59, 0xd1, 0x1d, 0x28, 0x64, 0xf9,
	0xaf, 0xbe, 0xfe, 0xdc, 0x9d, 0xbc, 0x50, 0xff, 0x7f, 0xe0, 0xb5, 0x25, 0x4a, 0xfc, 0x52, 0x69,
	0xae, 0xf2, 0xa5, 0x1c, 0x5c, 0xba, 0x87, 0x96, 0xbc, 0xe6, 0x0d, 0x3a, 0xe6, 0xcb, 0x8d, 0x91,
	0xab, 0x1f, 0xce, 0x14, 0xca, 0xdc, 0x3c, 0x31, 0xd7, 0xb7, 0xe6, 0xe3, 0x99, 0x35, 0xa7, 0xca,
	0x9a, 0x66, 0xfd, 0xea, 0x9f, 0xd6, 0x88, 0x67, 0xd9, 0xf1, 0x54, 0xab, 0x17, 0xa2, 0x25, 0x39,
	0x8c, 0x85, 0xca, 0x57, 0xda, 0xd3, 0xe9, 0x5b, 0x39, 0x98, 0x79, 0xac, 0x39, 0x56, 0x4e, 0x76,
	0x56, 0x1c, 0xb5, 0x8f, 0x19, 0x75, 0x6b, 0xa4, 0x19, 0x23, 0xb1, 0x42, 0xaa, 0xa5, 0xbf, 0x41,
	0xfb, 0x5e, 0x7d, 0x3a, 0xf3, 0xea, 0x54, 0x79, 0x25, 0xea, 0x73, 0x63, 0xbd, 0xea, 0xf4, 0xb7,
	0xda, 0x13, 0x6b, 0xb7, 0x1c, 0xfc, 0xb3, 0xde, 0x91, 0x36, 0x73, 0xe8, 0xf2, 0x48, 0x11, 0xb2,
	0x8e, 0x42, 0x97, 0xd9, 0x31, 0x5d, 0x7d, 0x33, 0x3e, 0x9c, 0x99, 0x71, 0xaa, 0xcc, 0xb8, 0x56,
	0xbf, 0x32, 0xd6, 0x0c, 0xdf, 0x91, 0x36, 0xb3, 0xe2, 0xce, 0xed, 0xcf, 0xfb, 0xb5, 0xd2, 0xde,
	0x7e, 0xad, 0xf4, 0x63, 0xbf, 0x56, 0x7a, 0x73, 0x50, 0x9b, 0xd8, 0x3b, 0xa8, 0x4d, 0x7c, 0x3f,
	0xa8, 0x4d, 0x3c, 0x99, 0x1d, 0x3b, 0xc9, 0x8e, 0x45, 0xdf, 0x9a, 0xee, 0xfd, 0x3d, 0x2d, 0xfe,
	0x0e, 0x00, 0x00, 0xff, 0xff, 0x84, 0x24, 0x9a, 0xd7, 0xb8, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgApiClient is the client API for MsgApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgApiClient interface {
	// Submit create liquidity pool message.
	CreateLiquidityPoolApi(ctx context.Context, in *MsgCreateLiquidityPoolRequest, opts ...grpc.CallOption) (*MsgCreateLiquidityPoolResponse, error)
	// Submit deposit to the liquidity pool batch
	DepositToLiquidityPoolApi(ctx context.Context, in *MsgDepositToLiquidityPoolRequest, opts ...grpc.CallOption) (*MsgDepositToLiquidityPoolResponse, error)
	// Submit withdraw from to the liquidity pool batch
	WithdrawFromLiquidityPoolApi(ctx context.Context, in *MsgWithdrawFromLiquidityPoolRequest, opts ...grpc.CallOption) (*MsgWithdrawFromLiquidityPoolResponse, error)
	// Submit swap to the liquidity pool batch
	SwapApi(ctx context.Context, in *MsgSwapRequest, opts ...grpc.CallOption) (*MsgSwapResponse, error)
}

type msgApiClient struct {
	cc grpc1.ClientConn
}

func NewMsgApiClient(cc grpc1.ClientConn) MsgApiClient {
	return &msgApiClient{cc}
}

func (c *msgApiClient) CreateLiquidityPoolApi(ctx context.Context, in *MsgCreateLiquidityPoolRequest, opts ...grpc.CallOption) (*MsgCreateLiquidityPoolResponse, error) {
	out := new(MsgCreateLiquidityPoolResponse)
	err := c.cc.Invoke(ctx, "/tendermint.liquidity.MsgApi/CreateLiquidityPoolApi", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgApiClient) DepositToLiquidityPoolApi(ctx context.Context, in *MsgDepositToLiquidityPoolRequest, opts ...grpc.CallOption) (*MsgDepositToLiquidityPoolResponse, error) {
	out := new(MsgDepositToLiquidityPoolResponse)
	err := c.cc.Invoke(ctx, "/tendermint.liquidity.MsgApi/DepositToLiquidityPoolApi", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgApiClient) WithdrawFromLiquidityPoolApi(ctx context.Context, in *MsgWithdrawFromLiquidityPoolRequest, opts ...grpc.CallOption) (*MsgWithdrawFromLiquidityPoolResponse, error) {
	out := new(MsgWithdrawFromLiquidityPoolResponse)
	err := c.cc.Invoke(ctx, "/tendermint.liquidity.MsgApi/WithdrawFromLiquidityPoolApi", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgApiClient) SwapApi(ctx context.Context, in *MsgSwapRequest, opts ...grpc.CallOption) (*MsgSwapResponse, error) {
	out := new(MsgSwapResponse)
	err := c.cc.Invoke(ctx, "/tendermint.liquidity.MsgApi/SwapApi", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgApiServer is the server API for MsgApi service.
type MsgApiServer interface {
	// Submit create liquidity pool message.
	CreateLiquidityPoolApi(context.Context, *MsgCreateLiquidityPoolRequest) (*MsgCreateLiquidityPoolResponse, error)
	// Submit deposit to the liquidity pool batch
	DepositToLiquidityPoolApi(context.Context, *MsgDepositToLiquidityPoolRequest) (*MsgDepositToLiquidityPoolResponse, error)
	// Submit withdraw from to the liquidity pool batch
	WithdrawFromLiquidityPoolApi(context.Context, *MsgWithdrawFromLiquidityPoolRequest) (*MsgWithdrawFromLiquidityPoolResponse, error)
	// Submit swap to the liquidity pool batch
	SwapApi(context.Context, *MsgSwapRequest) (*MsgSwapResponse, error)
}

// UnimplementedMsgApiServer can be embedded to have forward compatible implementations.
type UnimplementedMsgApiServer struct {
}

func (*UnimplementedMsgApiServer) CreateLiquidityPoolApi(ctx context.Context, req *MsgCreateLiquidityPoolRequest) (*MsgCreateLiquidityPoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLiquidityPoolApi not implemented")
}
func (*UnimplementedMsgApiServer) DepositToLiquidityPoolApi(ctx context.Context, req *MsgDepositToLiquidityPoolRequest) (*MsgDepositToLiquidityPoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DepositToLiquidityPoolApi not implemented")
}
func (*UnimplementedMsgApiServer) WithdrawFromLiquidityPoolApi(ctx context.Context, req *MsgWithdrawFromLiquidityPoolRequest) (*MsgWithdrawFromLiquidityPoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WithdrawFromLiquidityPoolApi not implemented")
}
func (*UnimplementedMsgApiServer) SwapApi(ctx context.Context, req *MsgSwapRequest) (*MsgSwapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SwapApi not implemented")
}

func RegisterMsgApiServer(s grpc1.Server, srv MsgApiServer) {
	s.RegisterService(&_MsgApi_serviceDesc, srv)
}

func _MsgApi_CreateLiquidityPoolApi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateLiquidityPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgApiServer).CreateLiquidityPoolApi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tendermint.liquidity.MsgApi/CreateLiquidityPoolApi",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgApiServer).CreateLiquidityPoolApi(ctx, req.(*MsgCreateLiquidityPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgApi_DepositToLiquidityPoolApi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDepositToLiquidityPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgApiServer).DepositToLiquidityPoolApi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tendermint.liquidity.MsgApi/DepositToLiquidityPoolApi",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgApiServer).DepositToLiquidityPoolApi(ctx, req.(*MsgDepositToLiquidityPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgApi_WithdrawFromLiquidityPoolApi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgWithdrawFromLiquidityPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgApiServer).WithdrawFromLiquidityPoolApi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tendermint.liquidity.MsgApi/WithdrawFromLiquidityPoolApi",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgApiServer).WithdrawFromLiquidityPoolApi(ctx, req.(*MsgWithdrawFromLiquidityPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgApi_SwapApi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSwapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgApiServer).SwapApi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tendermint.liquidity.MsgApi/SwapApi",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgApiServer).SwapApi(ctx, req.(*MsgSwapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MsgApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tendermint.liquidity.MsgApi",
	HandlerType: (*MsgApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLiquidityPoolApi",
			Handler:    _MsgApi_CreateLiquidityPoolApi_Handler,
		},
		{
			MethodName: "DepositToLiquidityPoolApi",
			Handler:    _MsgApi_DepositToLiquidityPoolApi_Handler,
		},
		{
			MethodName: "WithdrawFromLiquidityPoolApi",
			Handler:    _MsgApi_WithdrawFromLiquidityPoolApi_Handler,
		},
		{
			MethodName: "SwapApi",
			Handler:    _MsgApi_SwapApi_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "msg.proto",
}
