// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tx.proto

package types

import (
	bytes "bytes"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgCreateLiquidityPool struct {
	PoolCreator       github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,1,opt,name=pool_creator,json=poolCreator,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"pool_creator,omitempty" yaml:"pool_creator"`
	PoolTypeIndex     uint32                                        `protobuf:"varint,2,opt,name=pool_type_index,json=poolTypeIndex,proto3" json:"pool_type_index,omitempty" yaml:"pool_type_index"`
	ReserveCoinDenoms []string                                      `protobuf:"bytes,3,rep,name=reserve_coin_denoms,json=reserveCoinDenoms,proto3" json:"reserve_coin_denoms,omitempty" yaml:"reserve_coin_denoms"`
	DepositCoins      []types.Coin                                  `protobuf:"bytes,4,rep,name=deposit_coins,json=depositCoins,proto3" json:"deposit_coins" yaml:"deposit_coins"`
}

func (m *MsgCreateLiquidityPool) Reset()         { *m = MsgCreateLiquidityPool{} }
func (m *MsgCreateLiquidityPool) String() string { return proto.CompactTextString(m) }
func (*MsgCreateLiquidityPool) ProtoMessage()    {}
func (*MsgCreateLiquidityPool) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fd2153dc07d3b5c, []int{0}
}
func (m *MsgCreateLiquidityPool) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateLiquidityPool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateLiquidityPool.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateLiquidityPool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateLiquidityPool.Merge(m, src)
}
func (m *MsgCreateLiquidityPool) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateLiquidityPool) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateLiquidityPool.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateLiquidityPool proto.InternalMessageInfo

type MsgDepositToLiquidityPool struct {
	Depositor    github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,1,opt,name=depositor,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"depositor,omitempty" yaml:"depositor"`
	PoolID       uint64                                        `protobuf:"varint,2,opt,name=pool_id,json=poolId,proto3" json:"pool_id" yaml:"pool_id"`
	DepositCoins []types.Coin                                  `protobuf:"bytes,3,rep,name=deposit_coins,json=depositCoins,proto3" json:"deposit_coins" yaml:"deposit_coins"`
}

func (m *MsgDepositToLiquidityPool) Reset()         { *m = MsgDepositToLiquidityPool{} }
func (m *MsgDepositToLiquidityPool) String() string { return proto.CompactTextString(m) }
func (*MsgDepositToLiquidityPool) ProtoMessage()    {}
func (*MsgDepositToLiquidityPool) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fd2153dc07d3b5c, []int{1}
}
func (m *MsgDepositToLiquidityPool) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDepositToLiquidityPool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDepositToLiquidityPool.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDepositToLiquidityPool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDepositToLiquidityPool.Merge(m, src)
}
func (m *MsgDepositToLiquidityPool) XXX_Size() int {
	return m.Size()
}
func (m *MsgDepositToLiquidityPool) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDepositToLiquidityPool.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDepositToLiquidityPool proto.InternalMessageInfo

type MsgWithdrawFromLiquidityPool struct {
	Withdrawer github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,1,opt,name=withdrawer,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"withdrawer,omitempty" yaml:"withdrawer"`
	PoolID     uint64                                        `protobuf:"varint,2,opt,name=pool_id,json=poolId,proto3" json:"pool_id" yaml:"pool_id"`
	PoolCoin   []types.Coin                                  `protobuf:"bytes,3,rep,name=pool_coin,json=poolCoin,proto3" json:"pool_coin" yaml:"pool_coin"`
}

func (m *MsgWithdrawFromLiquidityPool) Reset()         { *m = MsgWithdrawFromLiquidityPool{} }
func (m *MsgWithdrawFromLiquidityPool) String() string { return proto.CompactTextString(m) }
func (*MsgWithdrawFromLiquidityPool) ProtoMessage()    {}
func (*MsgWithdrawFromLiquidityPool) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fd2153dc07d3b5c, []int{2}
}
func (m *MsgWithdrawFromLiquidityPool) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgWithdrawFromLiquidityPool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgWithdrawFromLiquidityPool.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgWithdrawFromLiquidityPool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgWithdrawFromLiquidityPool.Merge(m, src)
}
func (m *MsgWithdrawFromLiquidityPool) XXX_Size() int {
	return m.Size()
}
func (m *MsgWithdrawFromLiquidityPool) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgWithdrawFromLiquidityPool.DiscardUnknown(m)
}

var xxx_messageInfo_MsgWithdrawFromLiquidityPool proto.InternalMessageInfo

type MsgSwap struct {
	SwapRequester   github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,1,opt,name=swap_requester,json=swapRequester,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"swap_requester,omitempty" yaml:"swap_requester"`
	PoolID          uint64                                        `protobuf:"varint,2,opt,name=pool_id,json=poolId,proto3" json:"pool_id" yaml:"pool_id"`
	PoolTypeIndex   uint32                                        `protobuf:"varint,3,opt,name=pool_type_index,json=poolTypeIndex,proto3" json:"pool_type_index,omitempty" yaml:"pool_type_index"`
	SwapType        uint32                                        `protobuf:"varint,4,opt,name=swap_type,json=swapType,proto3" json:"swap_type,omitempty" yaml:"swap_type"`
	OfferCoin       types.Coin                                    `protobuf:"bytes,5,opt,name=offer_coin,json=offerCoin,proto3" json:"offer_coin" yaml:"offer_coin"`
	DemandCoinDenom string                                        `protobuf:"bytes,6,opt,name=demandCoinDenom,proto3" json:"demandCoinDenom,omitempty" yaml:"demand_coin_denom"`
	OrderPrice      github_com_cosmos_cosmos_sdk_types.Dec        `protobuf:"bytes,7,opt,name=order_price,json=orderPrice,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"order_price" yaml:"order_price"`
}

func (m *MsgSwap) Reset()         { *m = MsgSwap{} }
func (m *MsgSwap) String() string { return proto.CompactTextString(m) }
func (*MsgSwap) ProtoMessage()    {}
func (*MsgSwap) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fd2153dc07d3b5c, []int{3}
}
func (m *MsgSwap) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSwap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSwap.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSwap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSwap.Merge(m, src)
}
func (m *MsgSwap) XXX_Size() int {
	return m.Size()
}
func (m *MsgSwap) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSwap.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSwap proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCreateLiquidityPool)(nil), "tendermint.liquidity.MsgCreateLiquidityPool")
	proto.RegisterType((*MsgDepositToLiquidityPool)(nil), "tendermint.liquidity.MsgDepositToLiquidityPool")
	proto.RegisterType((*MsgWithdrawFromLiquidityPool)(nil), "tendermint.liquidity.MsgWithdrawFromLiquidityPool")
	proto.RegisterType((*MsgSwap)(nil), "tendermint.liquidity.MsgSwap")
}

func init() { proto.RegisterFile("tx.proto", fileDescriptor_0fd2153dc07d3b5c) }

var fileDescriptor_0fd2153dc07d3b5c = []byte{
	// 719 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x4b, 0x4f, 0xdb, 0x4c,
	0x14, 0x8d, 0x93, 0x7c, 0x81, 0x0c, 0x84, 0x87, 0xc9, 0x47, 0x4d, 0x84, 0x3c, 0x91, 0xa5, 0xb6,
	0xd9, 0xe0, 0x88, 0x76, 0xc7, 0xaa, 0x38, 0x29, 0x2a, 0x55, 0x53, 0x21, 0x83, 0x54, 0xa9, 0xaa,
	0x14, 0x39, 0x9e, 0x21, 0x8c, 0x48, 0x3c, 0xc6, 0x63, 0x08, 0xf9, 0x17, 0xfd, 0x09, 0xac, 0xfa,
	0x37, 0xba, 0x65, 0xc9, 0xb2, 0xea, 0x62, 0xd4, 0x86, 0x4d, 0xd5, 0xa5, 0x97, 0x95, 0x2a, 0x55,
	0xe3, 0x71, 0x5e, 0x2d, 0xea, 0x03, 0xb1, 0xf2, 0xdc, 0x39, 0xe7, 0x9e, 0xeb, 0x39, 0x77, 0x1e,
	0x60, 0x36, 0x3c, 0x37, 0xfd, 0x80, 0x86, 0x54, 0x2d, 0x86, 0xd8, 0x43, 0x38, 0xe8, 0x12, 0x2f,
	0x34, 0x3b, 0xe4, 0xe4, 0x94, 0x20, 0x12, 0xf6, 0x4b, 0xc5, 0x36, 0x6d, 0xd3, 0x98, 0x50, 0x15,
	0x23, 0xc9, 0x2d, 0xdd, 0x73, 0x29, 0xeb, 0x52, 0xd6, 0x94, 0x80, 0x4b, 0x89, 0x27, 0x01, 0xe3,
	0x7b, 0x1a, 0xac, 0x36, 0x58, 0xbb, 0x16, 0x60, 0x27, 0xc4, 0x2f, 0x86, 0x2a, 0x7b, 0x94, 0x76,
	0xd4, 0x63, 0x30, 0xef, 0x53, 0xda, 0x69, 0xba, 0x02, 0xa3, 0x81, 0xa6, 0x94, 0x95, 0xca, 0xbc,
	0xf5, 0x2c, 0xe2, 0x70, 0xa5, 0xef, 0x74, 0x3b, 0x5b, 0xc6, 0x24, 0x6a, 0x7c, 0xe3, 0x70, 0xa3,
	0x4d, 0xc2, 0xa3, 0xd3, 0x96, 0xe9, 0xd2, 0x6e, 0x55, 0xd6, 0x4b, 0x3e, 0x1b, 0x0c, 0x1d, 0x57,
	0xc3, 0xbe, 0x8f, 0x99, 0xb9, 0xed, 0xba, 0xdb, 0x08, 0x05, 0x98, 0x31, 0x7b, 0x4e, 0xe4, 0xd7,
	0x64, 0xba, 0x6a, 0x81, 0xc5, 0x58, 0x4e, 0xb0, 0x9a, 0xc4, 0x43, 0xf8, 0x5c, 0x4b, 0x97, 0x95,
	0x4a, 0xc1, 0x2a, 0x45, 0x1c, 0xae, 0x4e, 0xd4, 0x1b, 0x13, 0x0c, 0xbb, 0x20, 0x66, 0x0e, 0xfa,
	0x3e, 0xde, 0x15, 0xb1, 0xfa, 0x12, 0xac, 0x04, 0x98, 0xe1, 0xe0, 0x0c, 0x37, 0xc5, 0x0a, 0x9b,
	0x08, 0x7b, 0xb4, 0xcb, 0xb4, 0x4c, 0x39, 0x53, 0xc9, 0x5b, 0x7a, 0xc4, 0x61, 0x49, 0xea, 0xdc,
	0x40, 0x32, 0xec, 0xe5, 0x64, 0xb6, 0x46, 0x89, 0x57, 0x8f, 0xe7, 0xd4, 0x37, 0xa0, 0x80, 0xb0,
	0x4f, 0x19, 0x09, 0x63, 0x2a, 0xd3, 0xb2, 0xe5, 0x4c, 0x65, 0xee, 0xd1, 0x9a, 0x29, 0x57, 0x65,
	0xb6, 0x1c, 0x86, 0xcd, 0xb3, 0xcd, 0x16, 0x0e, 0x9d, 0x4d, 0x53, 0xe4, 0x59, 0xeb, 0x97, 0x1c,
	0xa6, 0x22, 0x0e, 0x8b, 0xb2, 0xd0, 0x54, 0xb6, 0x61, 0xcf, 0x27, 0xb1, 0xa0, 0xb2, 0xad, 0xec,
	0x97, 0x0b, 0xa8, 0x18, 0xef, 0xd2, 0x60, 0xad, 0xc1, 0xda, 0x75, 0x89, 0x1c, 0xd0, 0xe9, 0x16,
	0xb8, 0x20, 0x9f, 0xe4, 0x8c, 0xfc, 0x7f, 0x1a, 0x71, 0xb8, 0x34, 0x25, 0x7f, 0x2b, 0xf3, 0xc7,
	0xba, 0xea, 0x13, 0x30, 0x13, 0x3b, 0x4b, 0x50, 0x6c, 0x79, 0xd6, 0x7a, 0x38, 0xe0, 0x30, 0x27,
	0xea, 0xef, 0xd6, 0xbf, 0x72, 0x38, 0x04, 0x23, 0x0e, 0x17, 0x26, 0xfa, 0x40, 0x90, 0x61, 0xe7,
	0xc4, 0x68, 0x17, 0xfd, 0x6a, 0x54, 0xe6, 0xee, 0x8d, 0xba, 0x48, 0x83, 0xf5, 0x06, 0x6b, 0xbf,
	0x22, 0xe1, 0x11, 0x0a, 0x9c, 0xde, 0x4e, 0x40, 0xbb, 0xd3, 0x5e, 0x1d, 0x02, 0xd0, 0x4b, 0x40,
	0x3c, 0x34, 0x6b, 0x27, 0xe2, 0x70, 0x59, 0x96, 0x18, 0x63, 0xb7, 0x70, 0x6b, 0x42, 0xf9, 0x0e,
	0xec, 0xda, 0x03, 0x79, 0x79, 0x74, 0x28, 0xf1, 0xfe, 0x6c, 0x95, 0x96, 0x58, 0xb5, 0x34, 0x79,
	0xe8, 0x28, 0xf1, 0x0c, 0x7b, 0x36, 0x3e, 0x40, 0x94, 0x78, 0x89, 0x45, 0xef, 0xb3, 0x60, 0xa6,
	0xc1, 0xda, 0xfb, 0x3d, 0xc7, 0x57, 0x4f, 0xc0, 0x02, 0xeb, 0x39, 0x7e, 0x33, 0xc0, 0x27, 0xa7,
	0x98, 0x85, 0x23, 0x47, 0x9e, 0x47, 0x1c, 0xfe, 0x2f, 0x95, 0xa6, 0xf1, 0x5b, 0xb8, 0x52, 0x10,
	0x0a, 0xf6, 0x50, 0xe0, 0x0e, 0x8c, 0xb9, 0xe1, 0x12, 0xc8, 0xfc, 0xeb, 0x25, 0xb0, 0x09, 0xf2,
	0xf1, 0xc2, 0x04, 0x45, 0xcb, 0xc6, 0xd9, 0xc5, 0xb1, 0x7b, 0x23, 0xc8, 0xb0, 0x67, 0xc5, 0x58,
	0xe4, 0xa9, 0xfb, 0x00, 0xd0, 0xc3, 0x43, 0x1c, 0xc8, 0x86, 0xfc, 0x57, 0x56, 0x7e, 0xdf, 0x90,
	0xb5, 0xa4, 0x21, 0xc9, 0xc6, 0x1a, 0xa7, 0x1a, 0x76, 0x3e, 0x0e, 0x04, 0x4b, 0xdd, 0x01, 0x8b,
	0x08, 0x77, 0x1d, 0x0f, 0x8d, 0x2e, 0x14, 0x2d, 0x57, 0x56, 0x2a, 0x79, 0x6b, 0x3d, 0xe2, 0x50,
	0x1b, 0x6e, 0x7b, 0x41, 0x98, 0xb8, 0x87, 0x0c, 0xfb, 0xe7, 0x24, 0x15, 0x83, 0x39, 0x1a, 0x20,
	0x1c, 0x34, 0xfd, 0x80, 0xb8, 0x58, 0x9b, 0x89, 0xbb, 0x58, 0x17, 0xbf, 0xf0, 0x91, 0xc3, 0x07,
	0x7f, 0xd1, 0xb0, 0x3a, 0x76, 0x23, 0x0e, 0xd5, 0xe4, 0x67, 0xc7, 0x52, 0x86, 0x0d, 0xe2, 0x68,
	0x4f, 0x04, 0x72, 0x07, 0x59, 0xb5, 0xcb, 0xcf, 0x7a, 0xea, 0x72, 0xa0, 0x2b, 0x57, 0x03, 0x5d,
	0xf9, 0x34, 0xd0, 0x95, 0xb7, 0xd7, 0x7a, 0xea, 0xea, 0x5a, 0x4f, 0x7d, 0xb8, 0xd6, 0x53, 0xaf,
	0xef, 0x4f, 0x54, 0x1b, 0xbf, 0x3d, 0xd5, 0xd1, 0xdb, 0x23, 0x0b, 0xb6, 0x72, 0xf1, 0xcb, 0xf2,
	0xf8, 0x47, 0x00, 0x00, 0x00, 0xff, 0xff, 0x13, 0xe5, 0xc8, 0x05, 0xaa, 0x06, 0x00, 0x00,
}

func (this *MsgCreateLiquidityPool) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MsgCreateLiquidityPool)
	if !ok {
		that2, ok := that.(MsgCreateLiquidityPool)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.PoolCreator, that1.PoolCreator) {
		return false
	}
	if this.PoolTypeIndex != that1.PoolTypeIndex {
		return false
	}
	if len(this.ReserveCoinDenoms) != len(that1.ReserveCoinDenoms) {
		return false
	}
	for i := range this.ReserveCoinDenoms {
		if this.ReserveCoinDenoms[i] != that1.ReserveCoinDenoms[i] {
			return false
		}
	}
	if len(this.DepositCoins) != len(that1.DepositCoins) {
		return false
	}
	for i := range this.DepositCoins {
		if !this.DepositCoins[i].Equal(&that1.DepositCoins[i]) {
			return false
		}
	}
	return true
}
func (this *MsgDepositToLiquidityPool) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MsgDepositToLiquidityPool)
	if !ok {
		that2, ok := that.(MsgDepositToLiquidityPool)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.Depositor, that1.Depositor) {
		return false
	}
	if this.PoolID != that1.PoolID {
		return false
	}
	if len(this.DepositCoins) != len(that1.DepositCoins) {
		return false
	}
	for i := range this.DepositCoins {
		if !this.DepositCoins[i].Equal(&that1.DepositCoins[i]) {
			return false
		}
	}
	return true
}
func (this *MsgWithdrawFromLiquidityPool) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MsgWithdrawFromLiquidityPool)
	if !ok {
		that2, ok := that.(MsgWithdrawFromLiquidityPool)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.Withdrawer, that1.Withdrawer) {
		return false
	}
	if this.PoolID != that1.PoolID {
		return false
	}
	if len(this.PoolCoin) != len(that1.PoolCoin) {
		return false
	}
	for i := range this.PoolCoin {
		if !this.PoolCoin[i].Equal(&that1.PoolCoin[i]) {
			return false
		}
	}
	return true
}
func (this *MsgSwap) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MsgSwap)
	if !ok {
		that2, ok := that.(MsgSwap)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.SwapRequester, that1.SwapRequester) {
		return false
	}
	if this.PoolID != that1.PoolID {
		return false
	}
	if this.PoolTypeIndex != that1.PoolTypeIndex {
		return false
	}
	if this.SwapType != that1.SwapType {
		return false
	}
	if !this.OfferCoin.Equal(&that1.OfferCoin) {
		return false
	}
	if this.DemandCoinDenom != that1.DemandCoinDenom {
		return false
	}
	if !this.OrderPrice.Equal(that1.OrderPrice) {
		return false
	}
	return true
}
func (m *MsgCreateLiquidityPool) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateLiquidityPool) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateLiquidityPool) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DepositCoins) > 0 {
		for iNdEx := len(m.DepositCoins) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DepositCoins[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.ReserveCoinDenoms) > 0 {
		for iNdEx := len(m.ReserveCoinDenoms) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.ReserveCoinDenoms[iNdEx])
			copy(dAtA[i:], m.ReserveCoinDenoms[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.ReserveCoinDenoms[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.PoolTypeIndex != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.PoolTypeIndex))
		i--
		dAtA[i] = 0x10
	}
	if len(m.PoolCreator) > 0 {
		i -= len(m.PoolCreator)
		copy(dAtA[i:], m.PoolCreator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PoolCreator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDepositToLiquidityPool) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDepositToLiquidityPool) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDepositToLiquidityPool) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DepositCoins) > 0 {
		for iNdEx := len(m.DepositCoins) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DepositCoins[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.PoolID != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.PoolID))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Depositor) > 0 {
		i -= len(m.Depositor)
		copy(dAtA[i:], m.Depositor)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Depositor)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgWithdrawFromLiquidityPool) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgWithdrawFromLiquidityPool) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgWithdrawFromLiquidityPool) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PoolCoin) > 0 {
		for iNdEx := len(m.PoolCoin) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PoolCoin[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.PoolID != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.PoolID))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Withdrawer) > 0 {
		i -= len(m.Withdrawer)
		copy(dAtA[i:], m.Withdrawer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Withdrawer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSwap) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSwap) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSwap) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.OrderPrice.Size()
		i -= size
		if _, err := m.OrderPrice.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	if len(m.DemandCoinDenom) > 0 {
		i -= len(m.DemandCoinDenom)
		copy(dAtA[i:], m.DemandCoinDenom)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DemandCoinDenom)))
		i--
		dAtA[i] = 0x32
	}
	{
		size, err := m.OfferCoin.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if m.SwapType != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.SwapType))
		i--
		dAtA[i] = 0x20
	}
	if m.PoolTypeIndex != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.PoolTypeIndex))
		i--
		dAtA[i] = 0x18
	}
	if m.PoolID != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.PoolID))
		i--
		dAtA[i] = 0x10
	}
	if len(m.SwapRequester) > 0 {
		i -= len(m.SwapRequester)
		copy(dAtA[i:], m.SwapRequester)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SwapRequester)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreateLiquidityPool) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PoolCreator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.PoolTypeIndex != 0 {
		n += 1 + sovTx(uint64(m.PoolTypeIndex))
	}
	if len(m.ReserveCoinDenoms) > 0 {
		for _, s := range m.ReserveCoinDenoms {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	if len(m.DepositCoins) > 0 {
		for _, e := range m.DepositCoins {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgDepositToLiquidityPool) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Depositor)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.PoolID != 0 {
		n += 1 + sovTx(uint64(m.PoolID))
	}
	if len(m.DepositCoins) > 0 {
		for _, e := range m.DepositCoins {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgWithdrawFromLiquidityPool) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Withdrawer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.PoolID != 0 {
		n += 1 + sovTx(uint64(m.PoolID))
	}
	if len(m.PoolCoin) > 0 {
		for _, e := range m.PoolCoin {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgSwap) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SwapRequester)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.PoolID != 0 {
		n += 1 + sovTx(uint64(m.PoolID))
	}
	if m.PoolTypeIndex != 0 {
		n += 1 + sovTx(uint64(m.PoolTypeIndex))
	}
	if m.SwapType != 0 {
		n += 1 + sovTx(uint64(m.SwapType))
	}
	l = m.OfferCoin.Size()
	n += 1 + l + sovTx(uint64(l))
	l = len(m.DemandCoinDenom)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.OrderPrice.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreateLiquidityPool) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateLiquidityPool: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateLiquidityPool: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolCreator", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PoolCreator = append(m.PoolCreator[:0], dAtA[iNdEx:postIndex]...)
			if m.PoolCreator == nil {
				m.PoolCreator = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolTypeIndex", wireType)
			}
			m.PoolTypeIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PoolTypeIndex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReserveCoinDenoms", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReserveCoinDenoms = append(m.ReserveCoinDenoms, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositCoins", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DepositCoins = append(m.DepositCoins, types.Coin{})
			if err := m.DepositCoins[len(m.DepositCoins)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDepositToLiquidityPool) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDepositToLiquidityPool: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDepositToLiquidityPool: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Depositor", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Depositor = append(m.Depositor[:0], dAtA[iNdEx:postIndex]...)
			if m.Depositor == nil {
				m.Depositor = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolID", wireType)
			}
			m.PoolID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PoolID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositCoins", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DepositCoins = append(m.DepositCoins, types.Coin{})
			if err := m.DepositCoins[len(m.DepositCoins)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgWithdrawFromLiquidityPool) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgWithdrawFromLiquidityPool: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgWithdrawFromLiquidityPool: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Withdrawer", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Withdrawer = append(m.Withdrawer[:0], dAtA[iNdEx:postIndex]...)
			if m.Withdrawer == nil {
				m.Withdrawer = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolID", wireType)
			}
			m.PoolID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PoolID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolCoin", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PoolCoin = append(m.PoolCoin, types.Coin{})
			if err := m.PoolCoin[len(m.PoolCoin)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSwap) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSwap: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSwap: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SwapRequester", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SwapRequester = append(m.SwapRequester[:0], dAtA[iNdEx:postIndex]...)
			if m.SwapRequester == nil {
				m.SwapRequester = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolID", wireType)
			}
			m.PoolID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PoolID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolTypeIndex", wireType)
			}
			m.PoolTypeIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PoolTypeIndex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SwapType", wireType)
			}
			m.SwapType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SwapType |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OfferCoin", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.OfferCoin.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DemandCoinDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DemandCoinDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrderPrice", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.OrderPrice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
